server:
  port: 8080
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8088/realms/bank-realm}
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Forwarded-Proto, http
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: [GET,POST,PUT,DELETE,PATCH]
            allowed-headers: "*"
      routes:
        - id: account
          uri: ${ACCOUNT_URL:http://localhost:8081}
          predicates:
            - Path=/api/accounts/**
        - id: transfer
          uri: ${TRANSFER_URL:http://localhost:8082}
          predicates:
            - Path=/api/transfers/**
management:
  endpoints:
    web:
      exposure:
        include: health,info
