server:
  port: 8082

spring:
  application:
    name: transfer-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/transferdb}
    username: ${DB_USER:transfer}
    password: ${DB_PASS:transfer}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8088/realms/bank-realm}

clients:
  account-service:
    url: ${ACCOUNT_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info