apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 2
  selector:
    matchLabels: { app: account-service }
  template:
    metadata:
      labels: { app: account-service }
    spec:
      containers:
        - name: account-service
          image: IMAGE_ACCOUNT
          ports:
            - containerPort: 8081
          env:
            - name: KEYCLOAK_ISSUER_URI
              value: "http://keycloak:8080/realms/bank-realm"
            - name: DB_URL
              value: "jdbc:postgresql://account-db:5432/accountdb"
            - name: DB_USER
              value: "account"
            - name: DB_PASS
              value: "account"
